#!/bin/bash

## Description: Run PHPUnit tests
## Usage: phpunit [flags] [args]
## Example: `ddev phpunit` or `ddev phpunit --stop-on-failure`
## ExecRaw: true

if ! command -v phpunit >/dev/null; then
  echo "phpunit is not available. Please run `ddev composer-expand-install`."
  exit 1
fi

phpunit --bootstrap $PWD/$DDEV_DOCROOT/core/tests/bootstrap.php $DDEV_DOCROOT/modules/custom/steepbase "$@"
