#!/bin/bash

## Description: Symlink all root files/dirs into web/modules/custom/steepbase
## Usage: symlink-project
## Example: "ddev symlink-project"
## ExecRaw: true

export _WEB_ROOT=$DDEV_DOCROOT

cd "$DDEV_COMPOSER_ROOT" || exit
curl -OL https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/scripts/symlink_project.php

php symlink_project.php steepbase
rm -f symlink_project.php
